source 'https://rubygems.org'

gem 'sqlite3'

gem 'rails'

path = Pathname.new(__FILE__) + '..'

gem 'jointjs', path: path.dirname

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
