source 'https://rubygems.org'

gem 'sqlite3'

gem 'rails'
gem 'joint', path: '~/Develop/joint'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
