// Generated by CoffeeScript 1.6.3
(function() {
  var listen;

  this.Shiny = {
    attributeName: 'as'
  };

  this.Shiny.isDOM = function(el) {
    return el instanceof HTMLDocument || el instanceof HTMLElement;
  };

  listen = function(e) {
    if (e.type && e.type === 'DOMContentLoaded') {
      document.removeEventListener('DOMContentLoaded', listen);
    }
    Shiny.Watcher(document, {
      attributes: true,
      subtree: true,
      childList: true,
      attributeFilter: [Shiny.attributeName],
      characterData: true
    });
    return Shiny.Watcher().inspect(document.body);
  };

  if (document.readyState === 'complete') {
    listen();
  } else {
    document.addEventListener('DOMContentLoaded', listen);
  }

}).call(this);
