// Generated by CoffeeScript 1.6.3
(function() {
  var Models;

  Models = (function() {
    function Models() {}

    Models.prototype.klass = {};

    Models.prototype.add = function(kls, name) {
      if (name == null) {
        name = kls.name;
      }
      return this.klass[name] = kls;
    };

    return Models;

  })();

  Shiny.Models = new Models;

}).call(this);
